# Generated by Django 5.0.3 on 2024-04-19 21:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_pictures/default_pic.png', max_length=255, verbose_name='profile_pictures'),
        ),
    ]
